---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200

regionmap:
  layers:
    - name: "Milano Grid"
      url: "http://localhost:5601/bundles/milano-grid.geojson"
      fields:
        - name: "cellId"
          description: "Grid ID"
